# Generated by Django 4.0.5 on 2022-06-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamps_import',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='lamps_import',
            name='lng',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
    ]
