# Generated by Django 4.0.5 on 2022-06-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_lamps_import_lat_lamps_import_lng'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lamps_import',
            new_name='LampsUpload',
        ),
    ]
