# Generated by Django 4.0.5 on 2022-06-19 17:01

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_lamps_import_lampsupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampsCoccia00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('code', models.CharField(default='', max_length=20)),
                ('height', models.FloatField(default=7.9, verbose_name='Hauteur')),
                ('irc', models.IntegerField(default=74, verbose_name='Rendu de couleur')),
                ('power', models.IntegerField(default=149, verbose_name='Puissance')),
                ('colour', models.IntegerField(default=4999, verbose_name='Température de couleur')),
                ('on_motion', models.BooleanField(default=False, verbose_name='Détection de mouvement?')),
                ('lowering_night', models.IntegerField(default=0, verbose_name='Réduction nocturne (%)')),
                ('orientation', models.FloatField(default=0.0, verbose_name='Orientation')),
                ('horizontal_angle', models.FloatField(default=360.0, verbose_name='Angle horizontal')),
                ('nearest_way_dist', models.FloatField(default=-1.0, verbose_name='Distance voie la plus proche')),
                ('day_impact', models.FloatField(default=0.0, verbose_name='Impact (jour)')),
                ('night_impact', models.FloatField(default=0.0, verbose_name='Impact (nuit)')),
                ('lng', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('lat', models.FloatField(default=0.0, verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'Luminaire importé_Romain00',
                'verbose_name_plural': 'Luminaires importés_Romain00',
            },
        ),
        migrations.RenameModel(
            old_name='LampsUpload',
            new_name='LampsMairin00',
        ),
        migrations.AlterModelOptions(
            name='lampsmairin00',
            options={'verbose_name': 'Luminaire importé_Pascal00', 'verbose_name_plural': 'Luminaires importés_Pascal00'},
        ),
    ]
