# Generated by Django 4.0.4 on 2022-05-08 18:00

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=20)),
                ('position', django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([[0, 0], [0, 0]]), srid=4326)),
                ('name', models.CharField(default='', max_length=100)),
                ('width', models.FloatField(default=0.0)),
                ('lanes', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('code', models.CharField(default='', max_length=20)),
                ('height', models.FloatField(default=8.0)),
                ('irc', models.IntegerField(default=75)),
                ('power', models.IntegerField(default=150)),
                ('colour', models.IntegerField(default=5000)),
                ('on_motion', models.BooleanField(default=False)),
                ('lowering_night', models.IntegerField(default=0)),
                ('orientation', models.FloatField(default=-1.0)),
                ('nearest_way_dist', models.FloatField(default=-1.0)),
                ('day_impact', models.FloatField(default=0.0)),
                ('night_impact', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('taxon', models.CharField(default='', max_length=100)),
                ('planted_date', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
