# Generated by Django 4.0.4 on 2022-05-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='day_impact',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trees',
            name='night_impact',
            field=models.FloatField(default=0.0),
        ),
    ]
