# Generated by Django 4.0.4 on 2022-05-09 20:51

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollux', '0002_trees_day_impact_trees_night_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trees',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
